Merge obsolete software
* passwall : update to 3.0

update passwall po

passwall : fix bug

passwall : compatible with OpenWRT CC

passwall : fix use v2 udp node and open socks bug

passwall : fix ss ssr config error bug

passwall : fix bug

Fixed a bug where the subscription alias was too long.
Fixed an error after inherited configuration.

fix passwall makefile depends

passwall : change rules store path

save the configuration upgrade later and it will not be restored

unnecessary update

passwall : tcping detection node is preferred

More accurate detection

passwall : optimization detection

passwall : trojan link import and sub

Initial addition of Trojan link imports and subscriptions...
I don't know if it's standard...

passwall : fix last submitted bug

fix bug

passwall : fix subscribe

fix multiple subscribe bug
fix v2ray tls subscribe bug

passwall : fix ss subscribe

passwall : fix maybe not subscribe problem

passwall : fix bug

Update Makefile

Update subscription.sh

Update subscription.sh

Update Makefile

passwall : add use tcping option

passwall : remove repeat icon

passwall : swap redsocks2 to ipt2socks

passwall : fix bug and optimize script

passwall : update

optimized auto ping
fix chinadns + dns-forwarder

passwall : optimize

Update Makefile

passwall : add use tcping option

passwall : remove repeat icon

passwall : swap redsocks2 to ipt2socks

passwall : fix bug and optimize script

passwall : update

optimized auto ping
fix chinadns + dns-forwarder

passwall : optimize

passwall : remove dead DNS forwarding mode

update passwall makefile

passwall : update subscription script

Airport names can be noted as markers

passwall : optimize auto ping node

passwall : optimized test state

passwall : add a concise display node pattern

Notice : best is don't keep configuration upgrades.
Otherwise, please delete all subscription nodes before upgrading !!!

passwall : revert optimized test state

Co-Authored-By: ShanStone <shanstone@users.noreply.github.com>
Signed-off-by: Lienol <lawlienol@gmail.com>

* passwall : enhanced pdnsd mode

* passwall : enhanced chinadns-ng mode

* passwall : fix bug caused by bad operations

* passwall : open ssr as socks5 node the udp forwarding

* passwall : optimization script and fix bug

Happy New Year 2020 !

* psw : optimization script

* passwall : update to 3.1

1. Support some airport subscription bugs.
2. Support for custom v2ray-plugin opt.
3. Update the V2ray configuration

* passwall: proper encloser for inputer & break line

Co-Authored-By: peter-tank <peter-tank@users.noreply.github.com>

* passwall : update to 3.2

passwall : consummate chinadns-ng mode

passwall : open global and china white list for localhost agent mode

It is not recommended for use except in special cases,
otherwise, I will not answer any questions

passwall : optimize details

deblocking

passwall : show chinadns+dns2socks dns

do the customed binary path search in nodes configure either

Signed-off-by: peter-tank <30540412+peter-tank@users.noreply.github.com>

passwall : fix acl disable mode bug

passwall : fixed bug with duplicate subscriptions

Update Makefile

passwall : optimization script

Optimize webrestriction script

passwall : optimize same nodes ping

passwall : update

1. consummate chinadns-ng, now can customize domestic and foreign DNS.
2. localhost proxy supports UDP.

passwall : fix bug

Fixed a bug when again subscribe could cause node position

passwall : optimization script

passwall : update and fix bug

1. Compatible Firefox
2. Fixed issue when use gfwlist and game mode maybe not work
3. Fixed issue after saving configuration updates luci crashing and no network

passwall : fix magic bug when importing link nodes null remark name

passwall : optimized interface

passwall : support SSD subscription

passwall : update po

Unnecessary update

passwall : optimize details

Co-Authored-By: peter-tank <peter-tank@users.noreply.github.com>
Signed-off-by: Lienol <lawlienol@gmail.com>

* passwall : update to 3.3

passwall : update po

passwall : gfwlist ipset will not be lost when restart service

trojan: update ciphers and disable reuse_port in default

Signed-off-by: peter-tank <30540412+peter-tank@users.noreply.github.com>

passwall : update

normalize

passwall : update

let chinadns-ng use tcp by pdnsd
detail optimizing

passwall : chinadns-ng + pdnsd close cache

passwall : optimized code

From today on, passwall will stop updating. Regression development time to be determined...
Good luck, goodbye

passwall : format code & fix dns options on OpenWrt.org(19.07)

passwall : fix bug

passwall : fix bug and optimize

passwall : add v2ray balancing (#166)

* passwall : add v2ray balancing

document : https://toutyrater.github.io/app/balance.html

passwall : update (#171)

v2ray balancing support udp node and socks5 node
fix bug : Lienol/openwrt-package#168

passwall : fix nodes check bug

passwall : optimize

passwall : fix kcptun can't run bug (#178)

passwall : simplified interface

passwall : optimize details

passwall : optimize iptables sh

There will be major updates in the coming days.

passwall : Add ss plugin for subscription (#217)

* Update subscription.sh

Add ss plugin Lienol/openwrt-package#212

* Update Makefile

* Update subscription.sh

It still needs to be tested

Co-Authored-By: peter-tank <peter-tank@users.noreply.github.com>
Co-Authored-By: shanstone <shanstone@users.noreply.github.com>
Co-Authored-By: xiaorouji <xiaorouji@users.noreply.github.com>
Signed-off-by: Lienol <lawlienol@gmail.com>

* passwall : update to 3.5

* Add tcp and udp separate disable option.
* Delete game mode. Since some games still require TCP, it is better to use TCP nodes and UDP nodes and use the china whitelist mode
* Optimizing script variables
* Fix restart delay startup problem when main switch is not on

passwall : add reset config method

passwall : update to 3.5.3 (#223)

* update v2ray-plugin package

* add simple-obfs

Co-authored-by: Lienol <lawlienol@gmail.com>

passwall : fix subscription (#225)

passwall : update to 3.5.4

* Add trojan sni option
* Force ignore the parse file

passwall : fix bug

passwall : add no redir port option and fix bug

* add tcp and udp no redir port option
* fix bug

passwall : update

* Fixed some TCP v2ray node unavailability bug
* Optimized subscription script
* Optimized detection speed display

fix bug (#238)

fix node_port bug

passwall : update

* Use lua replace shell subscribe script (This file from luci-app-ssr-plus transplant to luci-app-passwall), Thank William Chan.
* Fix kcptun bug
* Code optimize

passwall : don't filter vps ip

passwall: optimize subscribe calc hashkey (#243)

passwall : fix subscribe and v2ray

passwall : fix bug

passwall : add common use port options

fix split function (#254)

Commit from coolsnowwolf/lede#3125
thanks to @SharerMax

passwall : fix big bug

 Optimization tips (#256)

passwall : support for trojan subscribe

passwall : fix brook ipt

passwall : Update app.sh (#259)

passwall: fix optimize iptables
Co-Authored-By: ShanStone <shanstone@users.noreply.github.com>
Co-Authored-By: William Chan <root@williamchan.me>
Co-Authored-By: klever1988 <klever1988@users.noreply.github.com>

* passwall : fix bug

passwall : support v2ray-plugin for ss

passwall : add group display option

passwall : describe

passwall : add show add mode option

passwall : replace chinadns to chinadns-ng

passwall : optimize pdnsd mode

Merry Christmas !

* add passwall

* passawll : update to 3.6.12

passwall : optimize details

passwall : fix haproxy interface option

passwall : fix some problems

passwall : Update subscribe.lua

fix tcping test command (#274)

passwall : rollback tcping (#277)

passwall : code optimize

passwall : Add firewall include script (#279)

passwall : fix gfw dnsmasq (#280)

dnsmasq service does not implement reload with reload command in my case

passwall : use lua rewrite update rules

fix uhttpd cbi() error log (#283)

daemon.err uhttpd[2381]: Model passwall/log returns SimpleForm but is dispatched via cbi()

passwall : add v2ray shunt and optimized ipt

passwall : fix tcp socks and optimize script

passwall : add brook websocket support

Brook WebSocket Transparent proxy need to use ipt2socks
Brook WebSocket don't support the UDP

passwall : tidy code

passwall : clear gfwlist ipset  when restart

passwall : prevent "talent" design

Update subscribe.lua (#294)

passwall : fix kcptun work in when multiple TCP nodes

Update app.sh

passwall : prevent sb airport bad thing

passwall: update rules

passwall: filter sb airport (#304)

passwall: node verify enhance and fix bug

passwall: modify style

passwall : update

* fix crontab subscribe bug
* fix acl udp no redir bug
* black and white list merge into acl
* filter node servers for invalid formats
* reopen auto switch menu
* reoptimize auto switch mechanism (now not support switch back node)

passwall: fix "_" host subscribe

passwall: reopen rules update

passwall: update

* optimize and fix bug by auto switch.
* unlock the china DNS.(again can play dns nested.)(When something goes wrong, don't look for me)

Co-Authored-By: ShanStone <shanstone@users.noreply.github.com>
Co-Authored-By: William Chan <root@williamchan.me>
Co-Authored-By: coolsnowwolf <coolsnowwolf@gmail.com>
Co-Authored-By: xiaorouji <xiaorouji@users.noreply.github.com>
Co-Authored-By: Ray <fgprodigal@users.noreply.github.com>

* passwall: add luci update option

Later update passwall will never have to recompile again !
But, dependspackages can not updated !!!

* passwall: fix get luci version

* passwall: update

* passwall: v2ray shunt update

* Take advantage of powerful v2ray shunt. now, v2ray shunt can use any protocol shunt.（important update）
* Smarter, customizable rules are ready to roll out （Stay tuned for）

* passwall: optimized node display

* passwall : optimize log

* passwall: fix rule button bug

* passwall: optimize subscribe

Co-Authored-By: William Chan <root@williamchan.me>

* passwall: api compatible with the new luci version

It's not the best way

* passwall: optimize log order

* passwall: fix subscribe bug

* passwall: fix typo (#328)

* passwall: update and fix bug

Not in the mood to describe...

* passwall: Update depens (#337)

update depens
fix sh: out of range

* passwall: update and fix bug

* fix when import node, will be delete all subscribe nodes bug
* prevent "talent" design +1

* passwall: subscribe compatible v2ray shunt (#344)

* passwall: fix Lienol/openwrt#183 (#346)

* passwall: update subscribe

* passwall: update

* node subscribe move to separate menu

* TCP UDP proxy mode can be set separately

* now can split into multiple haproxy groups

* passwall: Fix udp proxy (#361)

Co-authored-by: ShanStone <ShanStone@users.noreply.github.com>

* passwall: update to 3.6-29

* passwall: update

* complete v2ray protocol (add support ss socks http)
* fix some airport subscribe bug
* haproxy add new node set default haproxy port
* add diy filter airport subscribe keyword

* passwall: set default filter keyword

* passwall: Fix https://github.com/Lienol/openwrt-package/issues/368

* passwall: fix bug

* optimize passwall script

* passwall: Fix blacklist by default proxy (#400)

Co-authored-by: ShanStone <ShanStone@users.noreply.github.com>

* passwall: optimize subscribe

* passwall: chinadns-ng use fair mode

* Fix chinadns-ng when using default dns (#408)

Co-authored-by: ShanStone <ShanStone@users.noreply.github.com>

* Fix shadowsocks start fail when using domain name as address (#413)

* passwall: optimize

* passwall: add filter keyword main switch

* passwall: show the hostname also in mac addr col (#416)

* passwall: del useless ipv6 option (#417)

* passwall: add v2ray shunt Pre-Proxy  (#423)

* passwall: fix wget test bug (#425)

Co-authored-by: xiaorouji <60100640+xiaorouji@users.noreply.github.com>

* passwall: default select ssr-local (#430)

* passwall: add ACL

* passwall: optimize

* Update depand & optimize

* passwall: optimize lua table sort

* passwall: fix pre proxy firewall

* passwall: Add custom gfwlist and chnroute url

* Add custom gfwlist and chnroute url
* Add subscribe allowInsecure option

Co-authored-by: ShanStone <ShanStone@users.noreply.github.com>

* passwall: use curl instead of wget

* passwall: optimize code

* passwall: Add chnlist update url & fix bug

* Fix bug && speed ​​up download

* Add chnlist update url

Co-authored-by: ShanStone <ShanStone@users.noreply.github.com>

* passwall: complete main node check auto switch mechanism

* passwall: use lua gen SS(R) config

* passwall: let v2ray balancing and shunt into v2ray type

* passwall: socks5 type rename socks

* passwall: update status css

* passwall: add dns cache option

* passwall: add chinadns-ng fair mode option

* passwall: fix node_list set node div font fuzzy problem

* passwall: optimize

* passwall: use uuid as cfgid prevent id changes

* passwall: add multi select nodes new features

* Can delete a selected node

* passwall: optimize and fix bug

* passwall: let socks node independent

* passwall: add github connection check

* passwall: fix dns2socks mode

* passwall: add select all nodes button

* passwall: optimize

* passwall: add node to top button

Co-authored-by: ShanStone <shanstone@users.noreply.github.com>
Co-authored-by: peter-tank <30540412+peter-tank@users.noreply.github.com>
Co-authored-by: peter-tank <peter-tank@users.noreply.github.com>
Co-authored-by: xiaorouji <xiaorouji@users.noreply.github.com>
Co-authored-by: William Chan <root@williamchan.me>
Co-authored-by: klever1988 <klever1988@users.noreply.github.com>
Co-authored-by: coolsnowwolf <coolsnowwolf@gmail.com>
Co-authored-by: Ray <fgprodigal@users.noreply.github.com>
Co-authored-by: ShanStone <31815718+ShanStone@users.noreply.github.com>
Co-authored-by: xiaorouji <60100640+xiaorouji@users.noreply.github.com>
Co-authored-by: Kuma <xiongshimin1997@126.com>
Co-authored-by: securecrt <securecrt2008@gmail.com>
Co-authored-by: hyird <31695447+hyird@users.noreply.github.com>